//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArklahomaLakes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Shippping { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AddTstamp { get; set; }
        public Nullable<System.DateTime> UpdTstamp { get; set; }
        public string CC_Card { get; set; }
        public Nullable<int> CC_Num { get; set; }
        public Nullable<System.DateTime> CC_ExpDate { get; set; }
        public Nullable<int> CC_CSV { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
